-- Phase 3: Legal Management parties involved and AI-assisted party suggestions.

CREATE TABLE IF NOT EXISTS legal_matter_party (
  legal_matter_party_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  legal_matter_id BIGINT UNSIGNED NOT NULL,
  party_role VARCHAR(40) NOT NULL,
  party_type VARCHAR(40) NOT NULL,
  employee_reference_id BIGINT UNSIGNED NULL,
  visitor_id BIGINT UNSIGNED NULL,
  external_name VARCHAR(255) NULL,
  organization_name VARCHAR(255) NULL,
  contact_information VARCHAR(255) NULL,
  notes TEXT NULL,
  source_document_id BIGINT UNSIGNED NULL,
  ai_suggested TINYINT(1) NOT NULL DEFAULT 0,
  confirmed_by_user_id BIGINT UNSIGNED NULL,
  confirmed_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at DATETIME NULL,
  KEY idx_legal_party_matter (legal_matter_id, deleted_at),
  KEY idx_legal_party_employee (employee_reference_id),
  KEY idx_legal_party_visitor (visitor_id),
  KEY idx_legal_party_role (party_role),
  CONSTRAINT fk_legal_party_matter FOREIGN KEY (legal_matter_id) REFERENCES legal_matter(legal_matter_id) ON DELETE CASCADE,
  CONSTRAINT fk_legal_party_employee FOREIGN KEY (employee_reference_id) REFERENCES employee_reference(employee_reference_id) ON DELETE SET NULL,
  CONSTRAINT fk_legal_party_visitor FOREIGN KEY (visitor_id) REFERENCES visitor(visitor_id) ON DELETE SET NULL,
  CONSTRAINT fk_legal_party_document FOREIGN KEY (source_document_id) REFERENCES document(document_id) ON DELETE SET NULL,
  CONSTRAINT fk_legal_party_confirmed_by FOREIGN KEY (confirmed_by_user_id) REFERENCES user_account(user_account_id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS legal_matter_party_suggestion (
  legal_matter_party_suggestion_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  legal_matter_id BIGINT UNSIGNED NOT NULL,
  suggestion_hash CHAR(64) NOT NULL,
  suggested_name VARCHAR(255) NOT NULL,
  suggested_organization VARCHAR(255) NULL,
  suggested_party_role VARCHAR(40) NOT NULL,
  suggested_party_type VARCHAR(40) NOT NULL,
  context TEXT NULL,
  confidence VARCHAR(20) NULL,
  source_document_id BIGINT UNSIGNED NULL,
  source_document_reference VARCHAR(80) NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
  reviewed_by_user_id BIGINT UNSIGNED NULL,
  reviewed_at DATETIME NULL,
  accepted_party_id BIGINT UNSIGNED NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_legal_party_suggestion_hash (legal_matter_id, suggestion_hash),
  KEY idx_legal_party_suggestion_matter (legal_matter_id, status),
  CONSTRAINT fk_legal_party_suggestion_matter FOREIGN KEY (legal_matter_id) REFERENCES legal_matter(legal_matter_id) ON DELETE CASCADE,
  CONSTRAINT fk_legal_party_suggestion_document FOREIGN KEY (source_document_id) REFERENCES document(document_id) ON DELETE SET NULL,
  CONSTRAINT fk_legal_party_suggestion_reviewer FOREIGN KEY (reviewed_by_user_id) REFERENCES user_account(user_account_id) ON DELETE SET NULL,
  CONSTRAINT fk_legal_party_suggestion_party FOREIGN KEY (accepted_party_id) REFERENCES legal_matter_party(legal_matter_party_id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
