-- Phase 4: Legal Actions & Deadlines with AI-assisted action suggestions.

CREATE TABLE IF NOT EXISTS legal_matter_action (
  legal_matter_action_id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  legal_matter_id bigint(20) unsigned NOT NULL,
  title varchar(255) NOT NULL,
  action_type varchar(50) NOT NULL,
  description text NULL,
  assigned_employee_reference_id bigint(20) unsigned NULL,
  due_at datetime NULL,
  status varchar(30) NOT NULL DEFAULT 'PENDING',
  source varchar(20) NOT NULL DEFAULT 'MANUAL',
  source_document_id bigint(20) unsigned NULL,
  source_document_version_id bigint(20) unsigned NULL,
  created_by_user_id bigint(20) unsigned NULL,
  completed_by_user_id bigint(20) unsigned NULL,
  completed_at datetime NULL,
  cancelled_by_user_id bigint(20) unsigned NULL,
  cancelled_at datetime NULL,
  cancellation_reason text NULL,
  created_at datetime NOT NULL DEFAULT current_timestamp(),
  updated_at datetime NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  deleted_at datetime NULL,
  PRIMARY KEY (legal_matter_action_id),
  KEY idx_legal_action_matter (legal_matter_id, status, due_at),
  KEY idx_legal_action_assignee (assigned_employee_reference_id),
  KEY idx_legal_action_source_document (source_document_id),
  KEY fk_legal_action_created_by (created_by_user_id),
  KEY fk_legal_action_completed_by (completed_by_user_id),
  KEY fk_legal_action_cancelled_by (cancelled_by_user_id),
  CONSTRAINT fk_legal_action_matter FOREIGN KEY (legal_matter_id) REFERENCES legal_matter (legal_matter_id) ON DELETE CASCADE,
  CONSTRAINT fk_legal_action_assignee FOREIGN KEY (assigned_employee_reference_id) REFERENCES employee_reference (employee_reference_id) ON DELETE SET NULL,
  CONSTRAINT fk_legal_action_source_document FOREIGN KEY (source_document_id) REFERENCES document (document_id) ON DELETE SET NULL,
  CONSTRAINT fk_legal_action_created_by FOREIGN KEY (created_by_user_id) REFERENCES user_account (user_account_id) ON DELETE SET NULL,
  CONSTRAINT fk_legal_action_completed_by FOREIGN KEY (completed_by_user_id) REFERENCES user_account (user_account_id) ON DELETE SET NULL,
  CONSTRAINT fk_legal_action_cancelled_by FOREIGN KEY (cancelled_by_user_id) REFERENCES user_account (user_account_id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS legal_matter_action_suggestion (
  legal_matter_action_suggestion_id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  legal_matter_id bigint(20) unsigned NOT NULL,
  suggestion_hash char(64) NOT NULL,
  suggested_title varchar(255) NOT NULL,
  suggested_action_type varchar(50) NOT NULL,
  suggested_description text NULL,
  suggested_due_at datetime NULL,
  date_basis varchar(255) NULL,
  source_context varchar(1000) NULL,
  source_document_id bigint(20) unsigned NULL,
  source_document_version_id bigint(20) unsigned NULL,
  confidence varchar(20) NULL,
  status varchar(30) NOT NULL DEFAULT 'PENDING',
  dismissal_reason varchar(255) NULL,
  reviewed_by_user_id bigint(20) unsigned NULL,
  reviewed_at datetime NULL,
  accepted_action_id bigint(20) unsigned NULL,
  created_at datetime NOT NULL DEFAULT current_timestamp(),
  updated_at datetime NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (legal_matter_action_suggestion_id),
  UNIQUE KEY uq_legal_action_suggestion_hash (legal_matter_id, suggestion_hash),
  KEY idx_legal_action_suggestion_matter (legal_matter_id, status),
  KEY idx_legal_action_suggestion_source_document (source_document_id),
  KEY fk_legal_action_suggestion_reviewer (reviewed_by_user_id),
  KEY fk_legal_action_suggestion_action (accepted_action_id),
  CONSTRAINT fk_legal_action_suggestion_matter FOREIGN KEY (legal_matter_id) REFERENCES legal_matter (legal_matter_id) ON DELETE CASCADE,
  CONSTRAINT fk_legal_action_suggestion_source_document FOREIGN KEY (source_document_id) REFERENCES document (document_id) ON DELETE SET NULL,
  CONSTRAINT fk_legal_action_suggestion_reviewer FOREIGN KEY (reviewed_by_user_id) REFERENCES user_account (user_account_id) ON DELETE SET NULL,
  CONSTRAINT fk_legal_action_suggestion_action FOREIGN KEY (accepted_action_id) REFERENCES legal_matter_action (legal_matter_action_id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
