-- Rules & Regulations integration for Legal Management.
-- Idempotent schema only. Review and apply manually; do not execute from Codex.

CREATE TABLE IF NOT EXISTS legal_rule_policy (
  legal_rule_policy_id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  policy_code varchar(80) NOT NULL,
  title varchar(255) NOT NULL,
  category varchar(100) NULL,
  status varchar(30) NOT NULL DEFAULT 'ACTIVE',
  source_document_id bigint(20) unsigned NULL,
  source_document_version_id bigint(20) unsigned NULL,
  created_by_user_id bigint(20) unsigned NULL,
  updated_by_user_id bigint(20) unsigned NULL,
  created_at datetime NOT NULL DEFAULT current_timestamp(),
  updated_at datetime NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  deleted_at datetime NULL,
  PRIMARY KEY (legal_rule_policy_id),
  UNIQUE KEY uq_legal_rule_policy_code (policy_code),
  KEY idx_legal_rule_policy_status (status, deleted_at),
  KEY idx_legal_rule_policy_category (category),
  KEY fk_legal_rule_policy_source_document (source_document_id),
  KEY fk_legal_rule_policy_source_version (source_document_version_id),
  KEY fk_legal_rule_policy_created_by (created_by_user_id),
  KEY fk_legal_rule_policy_updated_by (updated_by_user_id),
  CONSTRAINT fk_legal_rule_policy_source_document FOREIGN KEY (source_document_id) REFERENCES document (document_id) ON DELETE SET NULL,
  CONSTRAINT fk_legal_rule_policy_source_version FOREIGN KEY (source_document_version_id) REFERENCES document_version (document_version_id) ON DELETE SET NULL,
  CONSTRAINT fk_legal_rule_policy_created_by FOREIGN KEY (created_by_user_id) REFERENCES user_account (user_account_id) ON DELETE SET NULL,
  CONSTRAINT fk_legal_rule_policy_updated_by FOREIGN KEY (updated_by_user_id) REFERENCES user_account (user_account_id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS legal_rule_provision (
  legal_rule_provision_id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  legal_rule_policy_id bigint(20) unsigned NOT NULL,
  provision_code varchar(100) NOT NULL,
  section_title varchar(255) NULL,
  provision_text text NOT NULL,
  version_number int(10) unsigned NOT NULL DEFAULT 1,
  effective_from date NULL,
  effective_until date NULL,
  status varchar(30) NOT NULL DEFAULT 'ACTIVE',
  supersedes_provision_id bigint(20) unsigned NULL,
  source_document_id bigint(20) unsigned NULL,
  source_document_version_id bigint(20) unsigned NULL,
  created_by_user_id bigint(20) unsigned NULL,
  updated_by_user_id bigint(20) unsigned NULL,
  created_at datetime NOT NULL DEFAULT current_timestamp(),
  updated_at datetime NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  deleted_at datetime NULL,
  PRIMARY KEY (legal_rule_provision_id),
  UNIQUE KEY uq_legal_rule_provision_version (legal_rule_policy_id, provision_code, version_number),
  KEY idx_legal_rule_provision_policy (legal_rule_policy_id, status, deleted_at),
  KEY idx_legal_rule_provision_code (provision_code),
  KEY idx_legal_rule_provision_effective (effective_from, effective_until),
  KEY fk_legal_rule_provision_supersedes (supersedes_provision_id),
  KEY fk_legal_rule_provision_source_document (source_document_id),
  KEY fk_legal_rule_provision_source_version (source_document_version_id),
  KEY fk_legal_rule_provision_created_by (created_by_user_id),
  KEY fk_legal_rule_provision_updated_by (updated_by_user_id),
  CONSTRAINT fk_legal_rule_provision_policy FOREIGN KEY (legal_rule_policy_id) REFERENCES legal_rule_policy (legal_rule_policy_id) ON DELETE CASCADE,
  CONSTRAINT fk_legal_rule_provision_supersedes FOREIGN KEY (supersedes_provision_id) REFERENCES legal_rule_provision (legal_rule_provision_id) ON DELETE SET NULL,
  CONSTRAINT fk_legal_rule_provision_source_document FOREIGN KEY (source_document_id) REFERENCES document (document_id) ON DELETE SET NULL,
  CONSTRAINT fk_legal_rule_provision_source_version FOREIGN KEY (source_document_version_id) REFERENCES document_version (document_version_id) ON DELETE SET NULL,
  CONSTRAINT fk_legal_rule_provision_created_by FOREIGN KEY (created_by_user_id) REFERENCES user_account (user_account_id) ON DELETE SET NULL,
  CONSTRAINT fk_legal_rule_provision_updated_by FOREIGN KEY (updated_by_user_id) REFERENCES user_account (user_account_id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS legal_matter_rule_basis (
  legal_matter_rule_basis_id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  legal_matter_id bigint(20) unsigned NOT NULL,
  legal_rule_policy_id bigint(20) unsigned NULL,
  legal_rule_provision_id bigint(20) unsigned NULL,
  policy_code_snapshot varchar(80) NOT NULL,
  policy_title_snapshot varchar(255) NOT NULL,
  category_snapshot varchar(100) NULL,
  provision_code_snapshot varchar(100) NOT NULL,
  section_title_snapshot varchar(255) NULL,
  provision_text_snapshot text NOT NULL,
  version_number_snapshot int(10) unsigned NOT NULL,
  effective_from_snapshot date NULL,
  effective_until_snapshot date NULL,
  linked_by_user_id bigint(20) unsigned NULL,
  linked_at datetime NOT NULL DEFAULT current_timestamp(),
  rationale text NULL,
  source varchar(30) NOT NULL DEFAULT 'MANUAL',
  created_at datetime NOT NULL DEFAULT current_timestamp(),
  updated_at datetime NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  deleted_at datetime NULL,
  active_link_key tinyint(1) AS (CASE WHEN deleted_at IS NULL THEN 1 ELSE NULL END) STORED,
  PRIMARY KEY (legal_matter_rule_basis_id),
  UNIQUE KEY uq_legal_matter_rule_active_link (legal_matter_id, legal_rule_provision_id, active_link_key),
  KEY idx_legal_matter_rule_matter (legal_matter_id, deleted_at),
  KEY idx_legal_matter_rule_provision (legal_rule_provision_id),
  KEY fk_legal_matter_rule_policy (legal_rule_policy_id),
  KEY fk_legal_matter_rule_linked_by (linked_by_user_id),
  CONSTRAINT fk_legal_matter_rule_matter FOREIGN KEY (legal_matter_id) REFERENCES legal_matter (legal_matter_id) ON DELETE CASCADE,
  CONSTRAINT fk_legal_matter_rule_policy FOREIGN KEY (legal_rule_policy_id) REFERENCES legal_rule_policy (legal_rule_policy_id) ON DELETE SET NULL,
  CONSTRAINT fk_legal_matter_rule_provision FOREIGN KEY (legal_rule_provision_id) REFERENCES legal_rule_provision (legal_rule_provision_id) ON DELETE SET NULL,
  CONSTRAINT fk_legal_matter_rule_linked_by FOREIGN KEY (linked_by_user_id) REFERENCES user_account (user_account_id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
